<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQi5Uf7x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQi5Uf7x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQi5Uf7x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQi5Uf7x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQi5Uf7x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qi5Uf7x',
    'container.build_id' => '5227d485',
    'container.build_time' => 1683711293,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQi5Uf7x');
