<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerReYwA1v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerReYwA1v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerReYwA1v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerReYwA1v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerReYwA1v\App_KernelDevDebugContainer([
    'container.build_hash' => 'ReYwA1v',
    'container.build_id' => 'd8986b6e',
    'container.build_time' => 1683543105,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerReYwA1v');
